"""Write generated tests into the tests/generated/ quarantine directory.

Files land here untrusted. They are gitignored until reviewed, and only move
to tests/curated/ after the critique pass documented in
evaluation/EVALUATION.md. The two-directory structure IS the quality gate.

The writer refuses to write anything that doesn't parse — even though the
generator already validated, this module is the last line before disk and
must not depend on its caller having done the right thing.
"""

import re
from datetime import datetime, timezone
from pathlib import Path

from specgen.generator import GenerationResult, validate_python

DEFAULT_OUT_DIR = Path("tests") / "generated"

_SLUG_RE = re.compile(r"[^a-z0-9]+")


class WriterError(Exception):
    """Raised when a result is not safe to write."""


def generated_filename(method: str, path: str) -> str:
    """Map an endpoint to the convention test_{resource}_{method}.py.

    "/pet/{petId}" + GET -> test_pet_petid_get.py
    """
    slug = _SLUG_RE.sub("_", path.lower()).strip("_") or "root"
    return f"test_{slug}_{method.lower()}.py"


def _header(result: GenerationResult) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        f"# GENERATED by specgen — DO NOT EDIT IN PLACE\n"
        f"# Quarantined output: review, then promote a corrected copy to tests/curated/.\n"
        f"# Endpoint:       {result.endpoint.label}\n"
        f"# Model:          {result.model}\n"
        f"# Prompt version: {result.prompt_version}\n"
        f"# Generated at:   {generated_at}\n\n"
    )


def write_test(result: GenerationResult, out_dir: Path = DEFAULT_OUT_DIR) -> Path:
    """Write one validated GenerationResult to the quarantine directory."""
    if not result.valid or result.code is None:
        raise WriterError(
            f"Refusing to write invalid result for {result.endpoint.label}"
        )
    syntax_error = validate_python(result.code)
    if syntax_error is not None:
        raise WriterError(
            f"Refusing to write unparseable code for {result.endpoint.label}: {syntax_error}"
        )

    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / generated_filename(result.endpoint.method, result.endpoint.path)
    target.write_text(
        _header(result) + result.code.rstrip("\n") + "\n", encoding="utf-8"
    )
    return target
