name: Continuous Integration

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    test-reporting:
        name: Test & Report
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Cache Poetry
              uses: actions/cache@v3
              with:
                path: ~/.cache/pypoetry
                key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
                restore-keys: |
                    ${{ runner.os }}-poetry-
            
            - name: Set up Java (Required for Allure CLI)
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '11'
            
            - name: Install Allure CLI
              run: |
                set -eux
                ALLURE_VERSION=2.28.0
                curl -Lo allure-commandline.zip \
                    https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/${ALLURE_VERSION}/allure-commandline-${ALLURE_VERSION}.zip
                unzip -o allure-commandline.zip -d allure-cli
                echo "${PWD}/allure-cli/allure-${ALLURE_VERSION}/bin" >> $GITHUB_PATH
            
            - name: Setup Python 3.13
              uses: actions/setup-python@v4
              with:
                python-version: '3.13'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install poetry
                make install
            
            - name: Run tests and generate Allure report
              run: make all
            
            - name: Upload Allure Report artifact
              uses: actions/upload-artifact@v3
              with:
                name: allure-report
                path: ./allure-report
